# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{feedbag-grow20}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alvin Liang", "Axiombox", "David Moreno"]
  s.date = %q{2011-02-23}
  s.default_executable = %q{feedbag}
  s.description = %q{Fork of Feedbag, for feed discovery, using nokogiri}
  s.email = %q{alvin@grow20.com}
  s.executables = ["feedbag"]
  s.extra_rdoc_files = [
    "ChangeLog",
    "README.markdown",
    "TODO"
  ]
  s.files = [
    "COPYING",
    "ChangeLog",
    "README.markdown",
    "Rakefile",
    "TODO",
    "VERSION",
    "benchmark/rfeedfinder_benchmark.rb",
    "bin/feedbag",
    "feedbag.gemspec",
    "index.html",
    "lib/feedbag.rb",
    "test/atom_autodiscovery_test.rb",
    "test/feedbag_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/aliang/feedbag}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Fork of Feedbag}
  s.test_files = [
    "test/atom_autodiscovery_test.rb",
    "test/feedbag_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<active_support>, [">= 0"])
    else
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<active_support>, [">= 0"])
    end
  else
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<active_support>, [">= 0"])
  end
end

